### ISSUE TITLE
compile problems / CUDA

### ISSUE THREAD

**Issue by heikog** [cboots/RGBD-to-Mesh#2]
Hi,
for the project CUDA-Mesh i get the error:
CUDA 5.5.props not found
im running VS 2015 and have CUDA 8.0 installed.
You have any advice for me ?

**Comment by cboots** [comment]
Sounds like a project config issue. It was built against CUDA 5 and hasn't
been updated since.
Take a look at your build options, it's been too long since I've worked on
this to remember off top of my head what needs to change though.
